# Generated by Django 5.1.4 on 2025-10-06 18:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_application_fee', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('auto_approve_merchants', models.BooleanField(default=False)),
                ('auto_approve_products', models.BooleanField(default=False)),
                ('enable_merchant_applications', models.BooleanField(default=True)),
                ('enable_product_submissions', models.BooleanField(default=True)),
                ('enable_featured_products', models.BooleanField(default=True)),
                ('max_products_per_seller', models.PositiveIntegerField(default=100)),
                ('min_product_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('max_product_price', models.DecimalField(decimal_places=2, default=999999.99, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Settings',
                'verbose_name_plural': 'Marketplace Settings',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('crypto_wallet', 'Crypto Wallet'), ('digital_wallet', 'Digital Wallet')], max_length=20, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('electronics', 'Electronics Retailer'), ('clothing', 'Clothing & Accessories'), ('home_garden', 'Home & Garden'), ('books_media', 'Books & Media'), ('sports_outdoors', 'Sports & Outdoors'), ('health_beauty', 'Health & Beauty'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='merchant_documents/')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='merchant_documents/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Application',
                'verbose_name_plural': 'Merchant Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Accessories'), ('home_garden', 'Home & Garden'), ('books_media', 'Books & Media'), ('sports_outdoors', 'Sports & Outdoors'), ('health_beauty', 'Health & Beauty'), ('automotive', 'Automotive'), ('tools_hardware', 'Tools & Hardware'), ('toys_games', 'Toys & Games'), ('other', 'Other')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('seller_verified', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_count', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.merchantapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Submission',
                'verbose_name_plural': 'Product Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
